---
- name: install and configure monitor server dependencies
  hosts: tag_Function_locust__splunk
  sudo: yes
  vars:
    locustFile: "infra/tests/loadTests/sample_locust.py"
    splunk_connection_host: ip
  roles:
    - splunkWebMonitor
    - locustio