# install mysql on a single EC2 instance
---
- hosts: all
  sudo: yes
  roles:
    - common
    - git
    - pip


  vars_files:
    - vars/m2/mysql_defaults.yml


  tasks:
    - name: mysql-install | Install python-software-properties
      apt:
        pkg=python-software-properties
        state=present
        update_cache=yes
        cache_valid_time={{apt_cache_valid_time}}


    - name: mysql-install | Create mysql group
      group:
        name={{ mysql_group }}


    - name: mysql-install | Create mysql user
      user:
        name={{ mysql_user }}
        group={{ mysql_group }}
        createhome=no


    - name: mysql-install | Ensure mysql directories exist
      file:
        path="{{ item }}"
        state=directory
        owner={{ mysql_user }}
        group={{ mysql_group }}
        recurse=yes
      with_items:
        - "{{ mysql_data_dir }}"
        - "{{ mysql_log_dir }}"
        - "{{ mysql_sock_dir }}"



    - name: mysql-install | Comfigure elasticsearch
      template:
        src=templates/my.cnf.j2
        dest={{ mysql_conf_dir  }}/my.cnf
        owner={{ mysql_user }}
        group={{ mysql_group }}
        mode=0644
      when: mysql_conf_dir is defined
      #notify: restart elasticsearch


    - name: elastic-install | Comfigure /etc/default/elasticsearch
      template:
        src=templates/elasticsearch.default.j2
        dest=/etc/default/elasticsearch
        owner={{ elasticsearch_user }}
        group={{ elasticsearch_group }}
        mode=0644    
      #notify: restart elasticsearch


    - name: es-plugin-install
      shell: bin/plugin install mobz/elasticsearch-head
          chdir={{ elasticsearch_home_dir }}


    - name: start elasticsearch
      service: state=started name=elasticsearch enabled=true   
      sudo: true


    
        