# install mysql on a single EC2 instance
---
- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: install python 2.7
      raw: sudo apt-get -y install python-minimal
  roles:
    - common
    - git

  vars_files:
    - vars/m2/mysql_defaults.yml


  tasks:
    - name: mysql-install | Create mysql group
      group:
        name={{ mysql_group }}


    - name: mysql-install | Create mysql user
      user:
        name={{ mysql_user }}
        group={{ mysql_group }}
        createhome=no


    - name: mysql-install | Ensure mysql directories exist
      file:
        path="{{ item }}"
        state=directory
        owner={{ mysql_user }}
        group={{ mysql_group }}
        recurse=yes
      with_items:
        - "{{ mysql_data_dir }}"
        - "{{ mysql_log_dir }}"
        - "{{ mysql_sock_dir }}"


    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_passwd}}'
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_passwd }}' vtype='password'


    - name: Install Mysql
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - python-mysqldb


    - name: mysql-install | Comfigure mysql
      template:
        src=templates/my.cnf.j2
        dest={{ mysql_conf_dir  }}/my.cnf
        owner={{ mysql_user }}
        group={{ mysql_group }}
        mode=0644
      when: mysql_conf_dir is defined
      

    - name: start mysql
      service: state=started name=mysql enabled=true   
      sudo: true


    
        