---
- hosts: all
  sudo: yes
  roles:
    - common

  tasks:
    - name: make sure wheel group exists
      group:
            name=wheel
            state=present

    - name: allow wheel group to have passwordless sudo
      lineinfile: 
            "dest=/etc/sudoers
            state=present
            regexp='^%wheel'
            line='%wheel ALL=(ALL) NOPASSWD: ALL'
            validate='/usr/sbin/visudo -cf %s'"

    - name: create kafka user
      user: 
            name=kafka
            state=present
            createhome=yes
            groups=wheel
            append=yes

    - name: download kafka
      become: "yes"
      become_user: "kafka"
      get_url:
            url='http://mirror.cc.columbia.edu/pub/software/apache/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz'
            dest=/home/kafka


    - name: untar kafka download
      become: 'yes'
      become_user: 'kafka'
      command: tar -xvf kafka_2.11-0.8.2.1.tgz chdir=/home/kafka