---
- hosts: all
  gather_facts: no
  sudo: yes

  roles:
    - common
    - java

  tasks:
    - name: "FIX: ubuntu 16.04 LTS is missing some required modules"
      raw: apt-get install python-minimal aptitude -y
      become: true
      become_user: root
      become_method: sudo 

    - name: add repository
      apt_repository: repo='ppa:webupd8team/java'
      become: true
      become_user: root

    - name: update apt packages
      apt: 
           update_cache: yes


    - name: install zookeeper
      apt: name=zookeeperd state=present
